openapi: 3.0.0
info:
  title: Student Register API
  description: This simple API allows for modification of the student register, adding and removing students.
  contact:
    email: joachim.dekker@students.uva.nl
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: http://localhost:8080/tutorial/1.0.0
  description: Default server
paths:
  /student/{student_id}:
    get:
      summary: gets student
      description: Returns a single student
      operationId: get_student_by_id
      parameters:
      - name: student_id
        in: path
        description: the uid
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        "400":
          description: Invalid ID
        "404":
          description: Not found
      x-openapi-router-controller: swagger_server.controllers.default_controller
    delete:
      summary: deletes a student
      description: |
        delete a single student
      operationId: delete_student
      parameters:
      - name: student_id
        in: path
        description: the uid
        required: true
        style: simple
        explode: false
        schema:
          type: number
          format: integer
      responses:
        "200":
          description: Succesfully deleted student
        "400":
          description: Bad Request
        "404":
          description: Student with specified student_id cannot be found
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /student:
    post:
      summary: Add a new student
      description: Adds an item to the system
      operationId: add_student
      requestBody:
        description: Student item to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        "200":
          description: created
          content:
            application/json:
              schema:
                type: string
                format: uuid
                x-content-type: application/json
        "400":
          description: "invalid input, object invalid"
        "409":
          description: Already exists
      x-openapi-router-controller: swagger_server.controllers.default_controller
components:
  schemas:
    Student:
      required:
      - first_name
      - last_name
      type: object
      properties:
        student_id:
          type: number
          format: integer
          example: 15887715
        first_name:
          type: string
          example: Joachim
        last_name:
          type: string
          example: Dekker
        grade_records:
          type: array
          items:
            $ref: '#/components/schemas/GradeRecord'
      example:
        student_id: 15887715
        last_name: Dekker
        grade_records:
        - grade: 0.8008282
          subject_name: DevOps
        - grade: 0.8008282
          subject_name: DevOps
        first_name: Joachim
    GradeRecord:
      required:
      - grade
      - subject_name
      type: object
      properties:
        subject_name:
          type: string
          example: DevOps
        grade:
          maximum: 10
          minimum: 0
          type: number
          format: float
      example:
        grade: 0.8008282
        subject_name: DevOps

